pluginManagement {
    repositories {
        mavenCentral()
        gradlePluginPortal()
        maven { url 'https://repo.spring.io/milestone' }
        maven { url 'https://repo.spring.io/snapshot' }
        mavenLocal()
    }
}

dependencyResolutionManagement {
    repositories {
        mavenCentral()
        mavenLocal()
        maven { url 'https://packages.confluent.io/maven/' }
    }
}

rootProject.name = 'ecommerce-microservice'

include 'hdp-library'
include 'hdp-config-server'
include 'hdp-product-service'
include 'hdp-notification-service'
include 'hdp-order-service'
include 'hdp-discovery-service'
include 'hdp-customer-service'