spring:
  kafka:
    bootstrap-servers: localhost:9092 # ket noi vao mot broker, gui request lay metadata cua cluster
    listener:
      missing-topics-fatal: true # khong co topic fail luon
    consumer:
      group-id: group_id
      auto-offset-reset: earliest # Doc tu msg dau tien, chi co tac dung khi consumer chua offset
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      enable-auto-commit: false
      properties:
        allow.auto.create.topics: false # Khong tu dong tao topic

