plugins {
    id 'java'
    id 'org.springframework.boot' version '4.0.5'
    id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com.hdp'
version = '0.0.1-SNAPSHOT'
description = 'Notification Service'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

ext {
    set('lombokVersion', '1.18.42')
    set('archunitVersion', '1.3.0')
}

configurations {
    compileOnly {
        extendsFrom annotationProcessor
    }
}

dependencyManagement {
    imports {
        mavenBom 'org.springframework.boot:spring-boot-dependencies:4.0.5'
    }
}

repositories {
    mavenCentral()
    mavenLocal()
    maven { url 'https://packages.confluent.io/maven/' }
}

configurations.all {
    resolutionStrategy {
        force "org.projectlombok:lombok:${lombokVersion}"
    }
}

dependencies {
    implementation project(':hdp-library')
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.kafka:spring-kafka'
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

    // ArchUnit for architecture testing
    testImplementation 'com.tngtech.archunit:archunit-junit5:1.3.0'
}

tasks.named('test') {
    useJUnitPlatform()
}
