hdp:
  aws:
    region: ${AWS_REGION:ap-southeast-1}
    access-key-id: ${AWS_ACCESS_KEY_ID:}
    secret-access-key: ${AWS_SECRET_ACCESS_KEY:}
    endpoint: ${AWS_ENDPOINT:}
    presigned-url-expiration-minutes: ${AWS_PRESIGNED_URL_EXPIRATION_MINUTES:15}
    public-host: ${AWS_PUBLIC_HOST:}
    bucket: ${AWS_BUCKET:}
    path-style-access-enabled: ${AWS_PATH_STYLE_ACCESS_ENABLED:false}