decorator:
  datasource:
    datasource-proxy:
      multiline: false

spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5434/product_db}
    username: ${DB_USERNAME:hdp_user}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

    hikari:
      transaction-isolation: TRANSACTION_READ_COMMITTED
      initialization-fail-timeout: 1
      pool-name: HikariCP-Product
      auto-commit: false                                      # auto commit khi commit/rollback

      minimum-idle: 5
      maximum-pool-size: 20

      idle-timeout: 300000
      connection-timeout: 30000
      validation-timeout: 5000

      max-lifetime: 1800000

      leak-detection-threshold: 60000

      keepalive-time: 100000

      data-source-properties:
        reWriteBatchedInserts: true
        preparedStatementCacheQueries: 256
        preparedStatementCacheSizeMiB: 5
        prepareThreshold: 3
        binaryTransfer: true
        tcpKeepAlive: true
        socketTimeout: 30
        connectTimeout: 10
        stringtype: unspecified