spring:
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      database: ${REDIS_DB:0}
      timeout: 2s
      lettuce:
        shutdown-timeout: 100ms
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1