spring:
  jpa:
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
        highlight_sql: false
        order_inserts: true
        order_updates: true
        type:
          json_format: canonical # Normalizes JSON representation to a consistent (canonical) format when reading/writing, ensuring stable serialization for correct comparison (dirty checking) and avoiding unnecessary updates due to formatting differences
        jdbc:
          time-zone: UTC
          batch_size: ${JPA_BATCH_SIZE:15}
          batch_versioned_data: true # allow optimistic locking batch update
        query:
          query-plan-cache-max-size: ${JPA_QUERY_PLAN_CACHE_MAX_SIZE:4096}
          in_clause_parameter_padding: true # Enables padding of IN-clause parameters to improve query plan caching and performance. Like this IN (1, 2, 3, <unused>) instead of IN (1, 2, 3)
          fail_on_pagination_over_collection_fetch: true # Fails fast when pagination is used with collection fetch joins to prevent incorrect or duplicated results
        connection:
          provider_disables_autocommit: true
        generate_statistics:  true


